---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: tue
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - TV
  - Music
  - Podcasts
  - News
  - "App Store"
  - Freeform
dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 3
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 4
  - name: "Termius"
    path: "/Applications/Termius.app/"
    pos: 5
  - name: "Terminal"
    path: "/Applications/Utilities/Terminal.app"
    pos: 6

configure_sudoers: true

dotfiles_repo: git@github.com:LukeCallaghan/dotfiles-mac.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_version: main
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .zprofile
  - .gitignore
  - .gitconfig
  - .osx
  - .starship.toml
  - .starship_uptime.sh
  - .php_cs.config
  - .aliasesrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search
  - python@3.11
  - bandit
  - black
  - libpq
  - composer
  - unbound
  - gnupg
  - iperf3
  - isort
  - openjdk
  - pinentry-mac
  - putty
  - python-tk@3.11
  - thefuck
  - starship
  - cocoapods

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/bundle
  - homebrew/cask-fonts
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - sequel-ace
  - transmit
  - adobe-acrobat-reader
  - amethyst
  - angry-ip-scanner
  - audacity
  - db-browser-for-sqlite
  - docker
  - dotnet
  - font-fira-code-nerd-font
  - google-chrome
  - grammarly-desktop
  - bitwarden
  - microsoft-remote-desktop
  - powershell
  - ringcentral
  - spotify
  - teamviewer
  - temurin11
  - termius
  - unetbootin
  - visual-studio-code
  - wireshark
  - hpedrorodrigues/tools/dockutil
  - flutter
  - android-studio
  - tunnelblick

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages:
  - name: ansible-lint
    state: present # present/absent/latest, default: present
  # version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
