---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove:
  - Launchpad
  - Messages
  - Mail
  - Maps
  - Photos
  - Facetime
  - Calendar
  - Contacts
  - Reminders
  - TV
  - Music
  - Podcasts
  - News
  - "App Store"
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: true

dotfiles_repo: https://github.com/LukeCallaghan/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Documents/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .zprofile
  - .gitignore
  - .gitconfig
  - .osx

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search
  - python@3.11
  - bandit
  - black
  - libpq
  - composer
  - unbound
  - gnupg
  - iperf3
  - isort
  - openjdk
  - pinentry-mac
  - putty
  - python-tk@3.11
  - thefuck

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/bundle
  - homebrew/cask-fonts
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - sequel-ace
  - transmit
  - adobe-acrobat-reader
  - amethyst
  - angry-ip-scanner
  - audacity
  - db-browser-for-sqlite
  - docker
  - dotnet
  - font-fira-code-nerd-font
  - google-chrome
  - grammarly-desktop
  - lastpass
  - microsoft-remote-desktop
  - powershell
  - ringcentral
  - spotify
  - teamviewer
  - temurin11
  - unetbootin
  - visual-studio-code
  - wireshark
  - hpedrorodrigues/tools/dockutil

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

visual_studio_code_extensions:
  - alexcvzz.vscode-sqlite
  - Angular.ng-template
  - bmewburn.vscode-intelephense-client
  - calebporzio.better-phpunit
  - EditorConfig.EditorConfig
  - ikappas.composer
  - johnpapa.Angular2
  - junstyle.php-cs-fixer
  - leighlondon.eml
  - ms-azuretools.vscode-docker
  - ms-python.isort
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-toolsai.jupyter
  - ms-toolsai.vscode-jupyter-cell-tags
  - ms-toolsai.vscode-jupyter-slideshow
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode.powershell
  - ms-vscode.remote-explorer
  - mtxr.sqltools
  - mtxr.sqltools-driver-mssql
  - mtxr.sqltools-driver-mysql
  - mtxr.sqltools-driver-pg
  - mtxr.sqltools-driver-sqlite
  - phproberto.vscode-php-getters-setters
  - redhat.ansible
  - redhat.vscode-yaml
  - rexshi.phpdoc-comment-vscode-plugin
  - sourcery.sourcery
visual_studio_code_extensions_absent:
  - seanmcbreen.Spell
