---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: gantsign.visual-studio-code-extensions
      users:
      - username: luke
        visual_studio_code_extensions:
          - alexcvzz.vscode-sqlite
          - Angular.ng-template
          - bmewburn.vscode-intelephense-client
          - calebporzio.better-phpunit
          - EditorConfig.EditorConfig
          - ikappas.composer
          - johnpapa.Angular2
          - junstyle.php-cs-fixer
          - leighlondon.eml
          - ms-azuretools.vscode-docker
          - ms-python.isort
          - ms-python.python
          - ms-python.vscode-pylance
          - ms-python.black-formatter
          - ms-python.flake8
          - ms-toolsai.jupyter
          - ms-toolsai.vscode-jupyter-cell-tags
          - ms-toolsai.vscode-jupyter-slideshow
          - ms-vscode-remote.remote-ssh
          - ms-vscode-remote.remote-ssh-edit
          - ms-vscode.powershell
          - ms-vscode.remote-explorer
          - mtxr.sqltools
          - mtxr.sqltools-driver-mssql
          - mtxr.sqltools-driver-mysql
          - mtxr.sqltools-driver-pg
          - mtxr.sqltools-driver-sqlite
          - phproberto.vscode-php-getters-setters
          - redhat.ansible
          - redhat.vscode-yaml
          - rexshi.phpdoc-comment-vscode-plugin
        visual_studio_code_extensions_absent: []

  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - import_tasks: tasks/vscode-settings.yml
      tags: ['vscode_settings']
