---
# If the user installs GNU sed through homebrew the path is different.
- name: Register path to sed.
  command: which sed
  register: sed_which_result
  changed_when: false
  when: sed_path is undefined

- name: Define sed_path variable.
  set_fact:
    sed_path: "{{ sed_which_result.stdout }}"
  when: sed_path is undefined

- name: Set content of sudo file as fact
  set_fact:
    sudo_conf: "{{ lookup('file', '/etc/pam.d/sudo') }}"
  ignore_errors: true

- name: Set sudo via Touch ID if not setup
  become: true
  command: sed -i '' 's/auth       sufficient     pam_smartcard.so/auth       sufficient     pam_smartcard.so\nauth       sufficient     pam_tid.so/g' /etc/pam.d/sudo
  when: "'auth       sufficient     pam_tid.so' not in sudo_conf"
