---
- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: Remove existing VSCode settings file.
  file:
    path: "~/Library/Application\ Support/Code/User/settings.json"
    state: absent

- name: Link dotfiles into home folder.
  file:
    src: "{{ dotfiles_repo_local_destination }}/vscode/settings.json"
    dest: "~/Library/Application\ Support/Code/User/settings.json"
    state: link
    mode: 0644
  become: false
